# Generated by Django 3.1.5 on 2021-02-22 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('be_mid', models.IntegerField(max_length=100, verbose_name='被回复用户')),
                ('root', models.IntegerField(default=0, verbose_name='根评论')),
                ('parent', models.IntegerField(default=0, verbose_name='父评论')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('aid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid', to='article.article', verbose_name='评论的文章')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mid', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'comment',
            },
        ),
    ]
