# Generated by Django 3.1.5 on 2021-02-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='be_mid',
            field=models.IntegerField(verbose_name='被回复用户'),
        ),
    ]
