# Generated by Django 3.1.5 on 2021-02-23 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210223_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mid',
            new_name='author',
        ),
    ]
