# Generated by Django 3.1.5 on 2021-03-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210223_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='be_mid',
            field=models.IntegerField(default=0, verbose_name='被回复用户'),
        ),
    ]
